# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
# the first 10 terms will be: 1,2,3,5,8,13,21,34,55,89
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.


def count_digits_string(n):
    return len(str(abs(n)))

def fibonacci(n):
    a = 0
    b = 1
    if n < 0:
        print("Incorrect input")
    elif n == 0:
        return 0
    elif n == 1:
        return b
    else:
        for i in range(1, n):
            c = a + b
            a = b
            b = c
        return b

output = 0
length = 0

target = fibonacci(4782)
index = 0
while length < 1001:
    index += 1 
    fib_value = (fibonacci(index))
    length = count_digits_string(fib_value)
    print (f"{index}      :     {length}")

print (target)